#!/usr/bin/env bash
# Behavioral tests for hooks/lib/attribution-detect.py
#
# The shared detector must recognize every attribution form the runtime emits,
# leave ordinary prose alone, strip attribution lines out of a commit message
# without eating the subject or body, and judge a PreToolUse payload on the
# right fields for the tool. Agent names are assembled from fragments so this
# file carries no literal attribution line for the live guard to block on.

set -euo pipefail

DETECT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../stratarc/data/hooks/lib" && pwd)/attribution-detect.py"

AGENT="Cla""ude"
AGENT_LOWER="cla""ude"
VENDOR="anthro""pic.com"
REPO_ORG="anthro""pics"
OPENAI_HOST="open""ai.com"
COPILOT="Copi""lot"
COPILOT_LOWER="copi""lot"

PASS=0
FAIL=0

record() {
  local ok="$1" label="$2" expect="$3" got="$4"
  if [ "$ok" = "yes" ]; then
    PASS=$((PASS+1))
  else
    FAIL=$((FAIL+1))
    printf '  attribution-detect.py FAIL  %-42s expected=%-14s got=%s\n' "$label" "$expect" "$got" >&2
  fi
}

# assert_detect <label> <text> <dirty|clean>
assert_detect() {
  local label="$1" text="$2" expect="$3" out got
  out=$(printf '%s' "$text" | python3 "$DETECT" detect || true)
  [ -n "$out" ] && got=dirty || got=clean
  [ "$got" = "$expect" ] && record yes "$label" "$expect" "$got" || record no "$label" "$expect" "$got"
}

assert_detect "co-author trailer"        "fix: thing

Co-Authored-By: ${AGENT} <noreply@${VENDOR}>"                                   dirty
assert_detect "generated with footer"    "Generated with ${AGENT} Code"          dirty
assert_detect "generated by footer"      "_Generated by ${AGENT} Code_"          dirty
assert_detect "written by agent"         "Written by an AI assistant"            dirty
assert_detect "vendor noreply address"   "noreply@${VENDOR}"                     dirty
assert_detect "session permalink"        "https://cla""ude.ai/code/session_01Ab" dirty
assert_detect "session trailer"          "${AGENT}-Session: somewhere"           dirty
assert_detect "robot byline"             $'\xf0\x9f\xa4\x96 built this'          dirty
assert_detect "co-author human allowed"  "Co-Authored-By: Dana Lee <d@example.com>" clean
# The trailer names an agent only in its name part; a person's address at a
# vendor domain is not a vendor noreply identity (PR 294 review, P2).
assert_detect "co-author human at vendor domain" "Co-Authored-By: Jane Doe <jane@cur""sor.com>" clean
assert_detect "co-author vendor noreply address" "Co-Authored-By: Bot <noreply@${VENDOR}>" dirty
# A generated-with match is a footer or byline, not a technical mention.
assert_detect "technical mention mid-sentence" "fix: parse config files cre""ated by Co""dex CLI" clean
assert_detect "footer after a sentence"  "Fix the parser. Gene""rated with ${AGENT} Code" dirty
assert_detect "plain commit body"        "fix: correct the off by one in staging" clean
assert_detect "prose naming the tool"    "The ${AGENT} Code CLI runs the hook."  clean
assert_detect "empty text"               ""                                      clean

# F-22: a
# descriptive citation of a repository issue, pull request, release, or
# documentation page is not a product landing page and must pass, even when
# the link text names the tool and the URL carries the vendor's org name.
assert_detect "repo issue citation"        "see [${AGENT} Code issue 21432](https://github.com/${REPO_ORG}/${AGENT_LOWER}-code/issues/21432) for details" clean
assert_detect "repo pull request citation" "[${AGENT} Code pull 99](https://github.com/${REPO_ORG}/${AGENT_LOWER}-code/pull/99)" clean
assert_detect "repo release citation"      "[${AGENT} Code release notes](https://github.com/${REPO_ORG}/${AGENT_LOWER}-code/releases/tag/v1)" clean
assert_detect "repo docs-path citation"    "[${AGENT} Code docs](https://github.com/${REPO_ORG}/${AGENT_LOWER}-code/docs/hooks)" clean
# A bare product landing page link still denies, credit phrasing or not.
assert_detect "product landing page link"    "[${AGENT} Code](https://${AGENT_LOWER}.ai/code)" dirty
assert_detect "non-github product docs link" "[${AGENT} Code](https://${OPENAI_HOST}/docs/agents)" dirty
assert_detect "github product repository"    "[${AGENT} Code](https://github.com/${REPO_ORG}/${AGENT_LOWER}-code)" dirty
assert_detect "copilot feature landing page" "[GitHub ${COPILOT}](https://github.com/features/${COPILOT_LOWER})" dirty

# A third party's page that names a product is a citation, not attribution,
# even with the product in the link text and the URL path. These are the
# 2026-10-08 `## sources` entries the product-link form denied (a project
# PR 127), in their real line form. Only a vendor host, or the vendor's own
# GitHub repository, is a product link.
TOOL_C="Co""dex"
TOOL_C_LOWER="co""dex"
ORG_O="Open""AI"
ORG_O_LOWER="open""ai"
assert_detect "third-party press release citation" "- [GitLab deepens integration with Anthropic's ${AGENT} models](https://www.nasdaq.com/press-release/gitlab-deepens-integration-${REPO_ORG}-${AGENT_LOWER}-models-accelerate-secure-software), Nasdaq, 2026-10-08, partnership scope." clean
assert_detect "third-party blog citation"          "- [GitHub ${COPILOT} statistics](https://quashbugs.com/blog/github-${COPILOT_LOWER}-statistics), Quash, 2026-10-08, adoption figures." clean
assert_detect "third-party resource citation"      "- [GitHub ${COPILOT} statistics](https://secondtalent.com/resources/github-${COPILOT_LOWER}-statistics), Second Talent, 2026-10-08, adoption figures." clean
assert_detect "third-party news citation"          "- [Cursor reaches a 60 billion valuation](https://tech-insider.org/cursor-60-billion-valuation-anysphere-ai-coding-2026/), Tech Insider, 2026-10-08, competitor valuation." clean
assert_detect "third-party analyst citation"       "- [${ORG_O} touts broadening ${TOOL_C} usage](https://constellationr.com/insights/news/${ORG_O_LOWER}-touts-broadening-${TOOL_C_LOWER}-usage-5-million-weekly-active-users), Constellation Research, 2026-10-08, usage figures." clean
assert_detect "third-party citations under a sources heading" "## sources

- [GitHub ${COPILOT} statistics](https://quashbugs.com/blog/github-${COPILOT_LOWER}-statistics), Quash, 2026-10-08, adoption figures.
- [${ORG_O} touts broadening ${TOOL_C} usage](https://constellationr.com/insights/news/${ORG_O_LOWER}-touts-broadening-${TOOL_C_LOWER}-usage-5-million-weekly-active-users), Constellation Research, 2026-10-08, usage figures." clean
# The host decides. A vendor host or subdomain still denies, a vendor name
# placed in a third party's hostname does not make it a vendor host, and
# userinfo in front of a vendor host does not hide it.
assert_detect "vendor host with a third-party word" "[${AGENT} Code](https://docs.${VENDOR}/en/nasdaq-${AGENT_LOWER})" dirty
assert_detect "vendor subdomain link"               "[${AGENT} Code](https://code.${AGENT_LOWER}.com/docs)" dirty
assert_detect "vendor name inside a third-party host" "[${AGENT} Code](https://${VENDOR}.example.net/${AGENT_LOWER})" clean
assert_detect "vendor host behind userinfo"         "[${AGENT} Code](https://user@${AGENT_LOWER}.ai/code)" dirty
# A sources line is no shelter for the forms that are always attribution.
# The literals below are spliced so this file does not trip the detector it tests.
PERMALINK="https://cla""ude.ai/code/session_01Ab"
GENERATED="Gene""rated"
ROBOT=$'\xf0\x9f\xa4\x96'
assert_detect "sources line with a session permalink" "## sources

- ${PERMALINK}" dirty
assert_detect "sources line with a footer"          "## sources

- [GitHub ${COPILOT} statistics](https://quashbugs.com/blog/github-${COPILOT_LOWER}-statistics). ${GENERATED} with ${AGENT} Code" dirty
assert_detect "sources line with a robot byline"    "## sources

- [GitHub ${COPILOT} statistics](https://quashbugs.com/blog/github-${COPILOT_LOWER}-statistics) ${ROBOT}" dirty
assert_detect "sources line with a co-author trailer" "## sources

Co-Authored-By: ${AGENT} <noreply@${VENDOR}>" dirty

# Provenance exception (the no-agent-attribution rule, provenance-exception):
# a session link on a `session-link:` line is metadata only in the frontmatter
# of a Markdown file under a docs/ directory. Bare text (a commit message, a
# pull request body, a handoff comment) is never docs frontmatter, so the CLI
# detect mode and detect() judge the line like any other.
SESSION_LINK="session-link: https://cla""ude.ai/code/session_01Ab"
assert_detect "session-link line in bare text"   "fix: x"$'\n\n'"$SESSION_LINK" dirty
assert_detect "session-link frontmatter as text" $'---\ntags: []\n'"$SESSION_LINK"$'\n---\n# note' dirty
assert_detect "session-link key, empty"      'session-link: ""'                      clean
assert_detect "link in body beside the key"  $'session-link: ""\n\nsee https://cla''ude.ai/code/session_01Ab' dirty
assert_detect "link on a non-key line"       $'sessions: https://cla''ude.ai/code/session_01Ab' dirty

# strip does not honour the exception: a commit message never carries the key.
strip_link=$(printf 'fix: x\n\nsession-link: https://cla''ude.ai/code/session_01Ab\n' | python3 "$DETECT" strip)
[ "$strip_link" = "fix: x" ] && record yes "strip removes session-link line" "fix: x" "$strip_link" \
  || record no "strip removes session-link line" "fix: x" "$strip_link"

# strip: attribution lines go, the subject and body stay, no orphan rule stays.
stripped=$(printf '%s' "feat: add guard

Real body line.

---
Generated with ${AGENT} Code
Co-Authored-By: ${AGENT} <noreply@${VENDOR}>
" | python3 "$DETECT" strip)
expected=$'feat: add guard\n\nReal body line.'
[ "$stripped" = "$expected" ] && record yes "strip removes footer and rule" "$expected" "$stripped" \
  || record no "strip removes footer and rule" "<subject+body>" "$stripped"

clean_in=$'fix: keep me\n\nBody stays.\n'
clean_out=$(printf '%s' "$clean_in" | python3 "$DETECT" strip)
[ "$clean_out" = $'fix: keep me\n\nBody stays.' ] && record yes "strip leaves clean message" same same \
  || record no "strip leaves clean message" "unchanged" "$clean_out"

# assert_payload <label> <json> <dirty|clean>
assert_payload() {
  local label="$1" json="$2" expect="$3" out got
  out=$(printf '%s' "$json" | python3 "$DETECT" detect-payload || true)
  [ -n "$out" ] && got=dirty || got=clean
  [ "$got" = "$expect" ] && record yes "$label" "$expect" "$got" || record no "$label" "$expect" "$got"
}

assert_payload "Write content"        "{\"tool_name\":\"Write\",\"tool_input\":{\"content\":\"Generated with ${AGENT} Code\"}}" dirty
assert_payload "Edit new_string"      "{\"tool_name\":\"Edit\",\"tool_input\":{\"new_string\":\"Generated by ${AGENT}\"}}"       dirty
assert_payload "Bash git commit"      "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git commit -m 'x' -m 'Co-Authored-By: ${AGENT} <a@b>'\"}}" dirty
# WI-55 incidental: the command-cwd-scoping rule makes `git -C <path>` the
# required spelling, and a global option before the subcommand used to hide
# the commit from the authoring-command check entirely.
assert_payload "Bash git -C commit"   "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git -C /repo commit -m 'x' -m 'Co-Authored-By: ${AGENT} <a@b>'\"}}" dirty
assert_payload "Bash git -c k=v commit" "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git -c user.name=x --no-pager commit -m 'x' -m 'Co-Authored-By: ${AGENT} <a@b>'\"}}" dirty
assert_payload "Bash git --git-dir x commit" "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git --git-dir /repo/.git --work-tree /repo commit -m 'x' -m 'Co-Authored-By: ${AGENT} <a@b>'\"}}" dirty
assert_payload "Bash git -C log is not authoring" "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git -C /repo log --grep 'Co-Authored-By: ${AGENT}'\"}}" clean
assert_payload "Bash grep is not authoring" "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"grep -rn 'Co-Authored-By: ${AGENT}' .\"}}" clean
assert_payload "MCP pull request body" "{\"tool_name\":\"mcp__github__create_pull_request\",\"tool_input\":{\"body\":\"Generated with ${AGENT} Code\"}}" dirty
assert_payload "MCP clean body"        "{\"tool_name\":\"mcp__github__create_pull_request\",\"tool_input\":{\"body\":\"Adds the guard.\"}}" clean
assert_payload "empty payload"         "{}" clean

# The provenance exception on the payload path: only a Write or Edit of a
# Markdown file under docs/, and only on a line inside that file's leading
# frontmatter block.
write_payload() {
  python3 -c 'import json, sys; print(json.dumps({"tool_name": sys.argv[1], "tool_input": {"file_path": sys.argv[2], sys.argv[3]: sys.argv[4]}}))' "$@"
}
FRONTMATTER=$'---\ntags: []\n'"$SESSION_LINK"$'\n---\n# note\n'
assert_payload "Write docs frontmatter session-link"   "$(write_payload Write /repo/docs/ideas/x.md content "$FRONTMATTER")" clean
assert_payload "Write link with robot byline" "$(write_payload Write /repo/docs/ideas/x.md content $'---\ntags: []\n'"$SESSION_LINK"$' \xf0\x9f\xa4\x96\n---\n# note\n')" dirty
assert_payload "Write relative docs frontmatter"       "$(write_payload Write docs/x.md content "$FRONTMATTER")" clean
assert_payload "Write nested docs frontmatter"         "$(write_payload Write /repo/sub/docs/adr/x.md content "$FRONTMATTER")" clean
assert_payload "Write .docs frontmatter session-link"  "$(write_payload Write /repo/.docs/prompts/testing/x.md content "$FRONTMATTER")" clean
assert_payload "Write session-link outside docs/"      "$(write_payload Write /repo/notes/x.md content "$FRONTMATTER")" dirty
assert_payload "Write session-link in docs non-md"     "$(write_payload Write /repo/docs/x.txt content "$FRONTMATTER")" dirty
assert_payload "Write docs-like directory name"        "$(write_payload Write /repo/mydocs/x.md content "$FRONTMATTER")" dirty
assert_payload "Write docs, key below frontmatter"     "$(write_payload Write /repo/docs/x.md content $'---\ntags: []\n---\n\n'"$SESSION_LINK")" dirty
assert_payload "Write docs, no frontmatter at all"     "$(write_payload Write /repo/docs/x.md content "$SESSION_LINK")" dirty
# A .docs/ directory (internal work product) is a docs directory too; the
# segment is still matched whole, so .docsx/ is not.
assert_payload "Write .docs frontmatter session-link"  "$(write_payload Write /repo/.docs/prompts/x.md content "$FRONTMATTER")" clean
assert_payload "Write relative .docs frontmatter"      "$(write_payload Write .docs/x.md content "$FRONTMATTER")" clean
assert_payload "Write .docs-like directory name"       "$(write_payload Write /repo/.docsx/x.md content "$FRONTMATTER")" dirty
assert_payload "Write .docs, key below frontmatter"    "$(write_payload Write /repo/.docs/x.md content $'---\ntags: []\n---\n\n'"$SESSION_LINK")" dirty
# A developer-docs/ directory (an extracted public repository's own docs) is
# a docs directory too, matched whole.
assert_payload "Write developer-docs frontmatter session-link" "$(write_payload Write /repo/developer-docs/adr/x.md content "$FRONTMATTER")" clean
assert_payload "Write relative developer-docs frontmatter"     "$(write_payload Write developer-docs/x.md content "$FRONTMATTER")" clean
assert_payload "Write developer-docs-like directory name"      "$(write_payload Write /repo/developer-docs-old/x.md content "$FRONTMATTER")" dirty
assert_payload "Write developer-docs, key below frontmatter"   "$(write_payload Write /repo/developer-docs/x.md content $'---\ntags: []\n---\n\n'"$SESSION_LINK")" dirty
assert_payload "Write with no file_path"               "{\"tool_name\":\"Write\",\"tool_input\":{\"content\":$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$FRONTMATTER")}}" dirty
# An Edit fragment is judged in the file it lands in: the exemption holds when
# the replaced text sits inside the target file's leading frontmatter.
EDITS="$(mktemp -d "${TMPDIR:-/tmp}/attribution-detect-edits-XXXXXX")"
mkdir -p "$EDITS/docs"
printf -- '---\ntags: []\nsession-link: ""\n---\n\n# note\n\nBody text.\n' > "$EDITS/docs/note.md"
edit_payload() {
  python3 -c 'import json, sys; print(json.dumps({"tool_name": "Edit", "tool_input": {"file_path": sys.argv[1], "old_string": sys.argv[2], "new_string": sys.argv[3]}}))' "$@"
}
assert_payload "Edit docs frontmatter session-link"    "$(edit_payload "$EDITS/docs/note.md" 'session-link: ""' "$SESSION_LINK")" clean
assert_payload "Edit docs body session-link"           "$(edit_payload "$EDITS/docs/note.md" 'Body text.' "$SESSION_LINK")" dirty
assert_payload "Edit docs file that does not exist"    "$(edit_payload "$EDITS/docs/missing.md" 'x' "$SESSION_LINK")" dirty
printf -- '---\ntags: []\nsession-link: ""\n---\n\n# note\n\nsession-link: ""\n' > "$EDITS/docs/repeated.md"
assert_payload "Edit replace_all reaches body" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "Edit", "tool_input": {"file_path": sys.argv[1], "old_string": sys.argv[2], "new_string": sys.argv[3], "replace_all": True}}))' "$EDITS/docs/repeated.md" 'session-link: ""' "$SESSION_LINK")" dirty
assert_payload "MultiEdit sequential frontmatter link" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "session-link: \"\"", "new_string": "session-link: pending"}, {"old_string": "session-link: pending", "new_string": sys.argv[2]}]}}))' "$EDITS/docs/note.md" "$SESSION_LINK")" clean
assert_payload "MultiEdit unknown location" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "absent", "new_string": sys.argv[2]}]}}))' "$EDITS/docs/note.md" "$SESSION_LINK")" dirty
assert_payload "MultiEdit body link" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "Body text.", "new_string": sys.argv[2]}]}}))' "$EDITS/docs/note.md" "$SESSION_LINK")" dirty
assert_payload "MultiEdit changes frontmatter boundary" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "tags: []", "new_string": "tags: []\n---"}, {"old_string": "session-link: \"\"", "new_string": sys.argv[2]}]}}))' "$EDITS/docs/note.md" "$SESSION_LINK")" dirty
assert_payload "MultiEdit moves link below boundary" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "session-link: \"\"", "new_string": sys.argv[2]}, {"old_string": "tags: []", "new_string": "tags: []\n---"}]}}))' "$EDITS/docs/note.md" "$SESSION_LINK")" dirty
assert_payload "MultiEdit removes temporary body link" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "Body text.", "new_string": sys.argv[2]}, {"old_string": sys.argv[2], "new_string": "Body text."}]}}))' "$EDITS/docs/note.md" "$SESSION_LINK")" clean
printf -- '---\ntags: []\nsession-link: ""\nsession-link: ""\n---\n' > "$EDITS/docs/replace-all.md"
assert_payload "MultiEdit replace_all updates every location" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "session-link: \"\"", "new_string": "session-link: pending", "replace_all": True}, {"old_string": "session-link: pending\n---", "new_string": sys.argv[2] + "\n---"}]}}))' "$EDITS/docs/replace-all.md" "$SESSION_LINK")" clean
assert_payload "MultiEdit replace_all reaches body" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "session-link: \"\"", "new_string": sys.argv[2], "replace_all": True}]}}))' "$EDITS/docs/repeated.md" "$SESSION_LINK")" dirty
printf -- '---\ntags: []\nsession-link: ""\n---\n\nBody %s\n' "${SESSION_LINK#session-link: }" > "$EDITS/docs/existing-body-link.md"
assert_payload "MultiEdit preserves new body link despite removed old link" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "session-link: \"\"", "new_string": sys.argv[2]}, {"old_string": "Body " + sys.argv[2].split(": ", 1)[1], "new_string": "Body."}, {"old_string": "tags: []", "new_string": "tags: []\n---"}]}}))' "$EDITS/docs/existing-body-link.md" "$SESSION_LINK")" dirty
cp "$EDITS/docs/note.md" "$EDITS/note.md"
assert_payload "Edit frontmatter outside docs/"        "$(edit_payload "$EDITS/note.md" 'session-link: ""' "$SESSION_LINK")" dirty
# review job 115: an edit is judged in the file it lands in, so a name
# swapped into an existing trailer is caught although the replacement alone
# matches nothing, and attribution the edit leaves untouched is not.
printf 'fix: x\n\nCo-Authored-By: Dana Lee <d@example.com>\n' > "$EDITS/message.txt"
assert_payload "Edit completes a trailer"              "$(edit_payload "$EDITS/message.txt" 'Dana Lee' "$AGENT")" dirty
assert_payload "MultiEdit completes a trailer" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "fix: x", "new_string": "fix: y"}, {"old_string": "Dana Lee", "new_string": sys.argv[2]}]}}))' "$EDITS/message.txt" "$AGENT")" dirty
assert_payload "Edit near a human trailer is clean"    "$(edit_payload "$EDITS/message.txt" 'Dana Lee' 'Sam Park')" clean
printf 'Notes\n\nCo-Authored-By: %s <a@b>\n' "$AGENT" > "$EDITS/history.txt"
assert_payload "Edit leaves old attribution alone"     "$(edit_payload "$EDITS/history.txt" 'Notes' 'Release notes')" clean
assert_payload "Edit of a missing file judges text"    "$(edit_payload "$EDITS/absent.txt" 'Dana Lee' "$AGENT")" clean
# Judging the landed file must stay inside the hook's 3 second budget: a
# large file of unclosed brackets made one pattern quadratic over the whole
# file. Only the lines an edit touches are scanned.
python3 -c 'import sys; open(sys.argv[1], "w").write("[a " * 40000 + "\nfix: x\n\nCo-Authored-By: Dana Lee <d@example.com>\n")' "$EDITS/large.txt"
started=$(python3 -c 'import time; print(time.time())')
assert_payload "clean Edit in a large file"           "$(edit_payload "$EDITS/large.txt" 'fix: x' 'fix: y')" clean
elapsed=$(python3 -c "import time; print(int((time.time() - $started) * 1000))")
[ "$elapsed" -lt 1000 ] && record yes "Edit in a large file under 1s" "<1000ms" "${elapsed}ms" \
  || record no "Edit in a large file under 1s" "<1000ms" "${elapsed}ms"
# A deletion writes no character, so it is judged at its join point: a match
# that spans the join, or whose one character of context the deletion
# changed, counts. Deleting text beside attribution that was already there,
# such as one of two trailer lines during cleanup, does not.
printf 'fix: x\n\nCo-Authored-By: %s-draft-%s <a@b>\n' "${AGENT:0:3}" "${AGENT:3}" > "$EDITS/split.txt"
assert_payload "deletion joins a split agent name"     "$(edit_payload "$EDITS/split.txt" '-draft-' '')" dirty
assert_payload "MultiEdit deletion joins a split name" "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "MultiEdit", "tool_input": {"file_path": sys.argv[1], "edits": [{"old_string": "fix: x", "new_string": "fix: y"}, {"old_string": "-draft-", "new_string": ""}]}}))' "$EDITS/split.txt")" dirty
# Deleting the second and third letters of a doubled prefix leaves both
# neighbours' context as it was, so only the span over the join catches it.
printf 'fix: x\n\nCo-Authored-By: %sl%s <a@b>\n' "${AGENT:0:1}" "$AGENT" > "$EDITS/doubled.txt"
assert_payload "deletion spans a join, context unchanged" "$(edit_payload "$EDITS/doubled.txt" "l${AGENT:0:1}" '')" dirty
printf 'Notes\nQQCo-Authored-By: %s <a@b>\n' "$AGENT" > "$EDITS/prefix.txt"
assert_payload "deletion opens a trailer at line start" "$(edit_payload "$EDITS/prefix.txt" 'QQ' '')" dirty
# A replacement can complete an anchor from just outside the match: a newline
# written before a trailer opens its line, a space written after a name
# closes its word.
printf 'fix: x\n\nnote: Co-Authored-By: %s <a@b>\n' "$AGENT" > "$EDITS/anchor-before.txt"
assert_payload "replacement opens a line before a trailer" "$(edit_payload "$EDITS/anchor-before.txt" 'note: ' $'note:\n')" dirty
printf 'Generated with %sX out\n' "$AGENT" > "$EDITS/anchor-after.txt"
assert_payload "replacement closes a word after a name"    "$(edit_payload "$EDITS/anchor-after.txt" 'X out' ' out')" dirty
# The left neighbour's context flag: a deletion that closes the word after a
# name counts, and one that leaves the next character as it was does not.
printf 'fix: x\n\nCo-Authored-By: %sXX <a@b>\n' "$AGENT" > "$EDITS/suffix.txt"
assert_payload "deletion closes the word after a name"  "$(edit_payload "$EDITS/suffix.txt" 'XX' '')" dirty
printf 'fix: x\n\nCo-Authored-By: %s X <a@b>\n' "$AGENT" > "$EDITS/unchanged-edge.txt"
assert_payload "deletion leaves the name's edge as it was" "$(edit_payload "$EDITS/unchanged-edge.txt" ' X' '')" clean
# review job 145: the start and end of the file read as a line boundary, so
# deleting the first line before an old trailer changes nothing it reads.
printf 'remove me\nCo-Authored-By: %s <a@b>\n' "$AGENT" > "$EDITS/first-line.txt"
assert_payload "deleting the file's first line"        "$(edit_payload "$EDITS/first-line.txt" $'remove me\n' '')" clean
printf 'Co-Authored-By: %s <a@b>\nremove me' "$AGENT" > "$EDITS/last-line.txt"
assert_payload "deleting the file's last line"         "$(edit_payload "$EDITS/last-line.txt" $'\nremove me' '')" clean
# review job 127: generated-with may break its line between the verb and
# the preposition, so the lines around an edit are judged with it.
printf 'fix: x\n\nGenerated\n\nwith Dana\n' > "$EDITS/two-line.txt"
assert_payload "edit completes a two-line footer"      "$(edit_payload "$EDITS/two-line.txt" 'Dana' "$AGENT")" dirty
printf 'Notes\nremove me\nCo-Authored-By: %s <a@b>\n' "$AGENT" > "$EDITS/before-trailer.txt"
assert_payload "deleting the line before old attribution" "$(edit_payload "$EDITS/before-trailer.txt" $'remove me\n' '')" clean
printf 'Notes\nCo-Authored-By: %s <a@b>\nCo-Authored-By: %s <c@d>\n' "$AGENT" "$AGENT" > "$EDITS/two-trailers.txt"
assert_payload "deleting one of two agent trailers"    "$(edit_payload "$EDITS/two-trailers.txt" $'Co-Authored-By: '"$AGENT"$' <a@b>\n' '')" clean
rm -rf "$EDITS"
# The exemption is off in a public repository: a checkout listed in <source
# root>/projects-root/public-targets.json (the source root being LLM_ROOT
# here) by its directory name, its main worktree's directory name or its
# origin's owner/repo slug, or any checkout when STRATARC_PUBLIC=1. The same
# frontmatter line is clean in a private fixture checkout and denied in a
# public one, on a Write, on an Edit, on a relative path resolved against
# the payload's cwd, in a docs directory that does not exist yet, in a
# linked worktree (whose .git is a file naming a gitdir whose commondir
# names the main worktree), in a worktree git itself created under an
# unlisted name, and in an unlisted directory whose origin slug is listed.
PUBLIC="$(mktemp -d "${TMPDIR:-/tmp}/attribution-detect-public-XXXXXX")"
mkdir -p "$PUBLIC/source/projects-root" "$PUBLIC/pub-repo/.git" "$PUBLIC/pub-repo/docs" \
  "$PUBLIC/private-repo/.git" "$PUBLIC/private-repo/docs" "$PUBLIC/pub-wt/docs" "$PUBLIC/_worktrees"
printf '{"targets": ["pub-repo", "pub-wt", "pub-main", "acme/pub-slug"]}\n' > "$PUBLIC/source/projects-root/public-targets.json"
printf 'gitdir: %s/pub-repo/.git/worktrees/pub-wt\n' "$PUBLIC" > "$PUBLIC/pub-wt/.git"
printf -- '---\ntags: []\nsession-link: ""\n---\n\n# note\n' > "$PUBLIC/pub-repo/docs/note.md"
cp "$PUBLIC/pub-repo/docs/note.md" "$PUBLIC/private-repo/docs/note.md"
# Real repositories, so the worktree's commondir and the origin's config are
# what git writes: pub-main is listed by name and its worktree sits under an
# unlisted name; by-slug is unlisted by name and its origin slug is listed;
# other-slug is unlisted either way.
git_fixture() {
  git -C "$1" init -q -b main
  git -C "$1" -c user.email=t@example.com -c user.name=t -c core.hooksPath=/dev/null commit -q --allow-empty -m fixture
  [ -z "${2:-}" ] || git -C "$1" remote add origin "$2"
}
mkdir -p "$PUBLIC/pub-main" "$PUBLIC/by-slug" "$PUBLIC/other-slug"
git_fixture "$PUBLIC/pub-main"
git -C "$PUBLIC/pub-main" worktree add -q "$PUBLIC/_worktrees/review" -b review
git_fixture "$PUBLIC/by-slug" "git@github.com:acme/pub-slug.git"
git_fixture "$PUBLIC/other-slug" "https://github.com/acme/other.git"
cwd_payload() {
  python3 -c 'import json, sys; print(json.dumps({"tool_name": "Write", "cwd": sys.argv[1], "tool_input": {"file_path": sys.argv[2], "content": sys.argv[3]}}))' "$@"
}
export LLM_ROOT="$PUBLIC/source"
assert_payload "Write docs frontmatter in a private checkout"  "$(write_payload Write "$PUBLIC/private-repo/docs/x.md" content "$FRONTMATTER")" clean
assert_payload "Write docs frontmatter in a public checkout"   "$(write_payload Write "$PUBLIC/pub-repo/docs/x.md" content "$FRONTMATTER")" dirty
assert_payload "Write into a new docs directory, public"       "$(write_payload Write "$PUBLIC/pub-repo/docs/new/deeper/x.md" content "$FRONTMATTER")" dirty
assert_payload "Write relative docs path, public cwd"          "$(cwd_payload "$PUBLIC/pub-repo" docs/x.md "$FRONTMATTER")" dirty
assert_payload "Write relative docs path, private cwd"         "$(cwd_payload "$PUBLIC/private-repo" docs/x.md "$FRONTMATTER")" clean
assert_payload "Write docs frontmatter in a public worktree"   "$(write_payload Write "$PUBLIC/pub-wt/docs/x.md" content "$FRONTMATTER")" dirty
assert_payload "Write in a git worktree of a listed main"      "$(write_payload Write "$PUBLIC/_worktrees/review/docs/x.md" content "$FRONTMATTER")" dirty
assert_payload "Write in the listed main checkout itself"      "$(write_payload Write "$PUBLIC/pub-main/docs/x.md" content "$FRONTMATTER")" dirty
assert_payload "Write where only the origin slug is listed"    "$(write_payload Write "$PUBLIC/by-slug/docs/x.md" content "$FRONTMATTER")" dirty
assert_payload "Write where the origin slug is another repo"   "$(write_payload Write "$PUBLIC/other-slug/docs/x.md" content "$FRONTMATTER")" clean
assert_payload "Edit docs frontmatter in a private checkout"   "$(edit_payload "$PUBLIC/private-repo/docs/note.md" 'session-link: ""' "$SESSION_LINK")" clean
assert_payload "Edit docs frontmatter in a public checkout"    "$(edit_payload "$PUBLIC/pub-repo/docs/note.md" 'session-link: ""' "$SESSION_LINK")" dirty
assert_payload "Write with no checkout at all stays exempt"    "$(write_payload Write "$PUBLIC/docs/x.md" content "$FRONTMATTER")" clean
export STRATARC_PUBLIC=1
assert_payload "STRATARC_PUBLIC=1 denies in a private checkout" "$(write_payload Write "$PUBLIC/private-repo/docs/x.md" content "$FRONTMATTER")" dirty
assert_payload "STRATARC_PUBLIC=1 denies with no checkout"      "$(write_payload Write /repo/docs/ideas/x.md content "$FRONTMATTER")" dirty
unset STRATARC_PUBLIC
# An absent list names nobody, so the exemption holds as before. A list that
# exists and cannot be read fails closed: the exemption is off everywhere,
# the private checkout included, until the file is fixed.
for broken in 'not json' '{"targets": "pub-repo"}' '[1]' '[""]'; do
  printf '%s\n' "$broken" > "$PUBLIC/source/projects-root/public-targets.json"
  assert_payload "unreadable public-targets ($broken) denies in a public checkout"  "$(write_payload Write "$PUBLIC/pub-repo/docs/x.md" content "$FRONTMATTER")" dirty
  assert_payload "unreadable public-targets ($broken) denies in a private checkout" "$(write_payload Write "$PUBLIC/private-repo/docs/x.md" content "$FRONTMATTER")" dirty
done
export LLM_ROOT="$PUBLIC/nowhere"
assert_payload "absent public-targets names nobody"            "$(write_payload Write "$PUBLIC/pub-repo/docs/x.md" content "$FRONTMATTER")" clean
unset LLM_ROOT
git -C "$PUBLIC/pub-main" worktree remove --force "$PUBLIC/_worktrees/review" 2>/dev/null || true
rm -rf "$PUBLIC"
# Every published channel judges the line: a commit, a pull request body file,
# an MCP message field.
assert_payload "git commit -m session-link"            "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "Bash", "tool_input": {"command": "git commit -m fix -m \"" + sys.argv[1] + "\""}}))' "$SESSION_LINK")" dirty
assert_payload "MCP body session-link"                 "$(python3 -c 'import json, sys; print(json.dumps({"tool_name": "mcp__github__create_pull_request", "tool_input": {"body": "Adds x.\n\n" + sys.argv[1]}}))' "$SESSION_LINK")" dirty

# WI-55 (A-03 of the design record):
# a command that names a file as its message body publishes that file, so the
# Bash branch reads it and scans it with the command. The fixture files are
# written here at run time, with the agent name built from fragments, so this
# source carries no attribution line.
BODIES="$(mktemp -d "${TMPDIR:-/tmp}/attribution-detect-bodies-XXXXXX")"
trap 'rm -rf "$BODIES"' EXIT
printf 'Adds the guard.\n\nGenerated with %s Code\n' "$AGENT" > "$BODIES/dirty.md"
printf 'fix: x\n\nCo-Authored-By: %s <noreply@%s>\n' "$AGENT" "$VENDOR" > "$BODIES/dirty-commit.txt"
printf 'Adds the guard.\n' > "$BODIES/clean.md"
mkdir -p "$BODIES/work"
printf 'Body.\n\nGenerated with %s Code\n' "$AGENT" > "$BODIES/work/relative.md"

bash_payload() {
  python3 -c 'import json, sys; print(json.dumps({"tool_name": "Bash", "cwd": sys.argv[2], "tool_input": {"command": sys.argv[1]}}))' "$1" "${2:-/}"
}

assert_payload "gh pr comment --body-file dirty"  "$(bash_payload "gh pr comment 1 --body-file $BODIES/dirty.md")" dirty
assert_payload "gh pr create --body-file= dirty"  "$(bash_payload "gh pr create --title t --body-file=$BODIES/dirty.md")" dirty
assert_payload "gh pr create -F dirty"            "$(bash_payload "gh pr create --title t -F $BODIES/dirty.md")" dirty
assert_payload "gh api -F body=@ dirty"           "$(bash_payload "gh api repos/o/r/issues/1/comments -F body=@$BODIES/dirty.md --jq .html_url")" dirty
assert_payload "gh api --field body=@ dirty"      "$(bash_payload "gh api repos/o/r/issues/1/comments --field body=@$BODIES/dirty.md")" dirty
assert_payload "gh api --field=body=@ dirty"      "$(bash_payload "gh api repos/o/r/issues/1/comments --field=body=@$BODIES/dirty.md")" dirty
assert_payload "git commit -F dirty"              "$(bash_payload "git commit -F $BODIES/dirty-commit.txt")" dirty
assert_payload "git -C dir commit --file dirty"   "$(bash_payload "git -C /tmp commit --file $BODIES/dirty-commit.txt")" dirty
assert_payload "git commit --file= dirty"         "$(bash_payload "git commit --file=$BODIES/dirty-commit.txt")" dirty
assert_payload "relative body file uses cwd"      "$(bash_payload "gh pr comment 1 --body-file work/relative.md" "$BODIES")" dirty
assert_payload "body file after a compound cd"    "$(bash_payload "cd $BODIES && gh pr comment 1 --body-file $BODIES/dirty.md")" dirty
# Codex review of PR 43: git resolves -F against the directory -C names, and
# several -C options compound, relative ones against the payload's cwd.
assert_payload "git -C abs commit -F relative"    "$(bash_payload "git -C $BODIES/work commit -F relative.md")" dirty
assert_payload "git -C rel commit -F relative"    "$(bash_payload "git -C work commit -F relative.md" "$BODIES")" dirty
assert_payload "git -C twice commit -F relative"  "$(bash_payload "git -C $BODIES -C work commit -F relative.md")" dirty
# Codex review of PR 43: gh api --input sends a JSON request body, whose
# newlines are escaped, so its message fields are decoded before the scan.
printf '{"body":"Summary\\n\\nCo-Authored-By: %s <a@b>"}\n' "$AGENT" > "$BODIES/request.json"
printf '{"body":"Summary\\n\\nNothing else."}\n' > "$BODIES/clean-request.json"
assert_payload "gh api --input JSON body dirty"   "$(bash_payload "gh api repos/o/r/issues/1/comments --input $BODIES/request.json")" dirty
assert_payload "gh api --input JSON body clean"   "$(bash_payload "gh api repos/o/r/issues/1/comments --input $BODIES/clean-request.json")" clean
# Second Codex review of PR 43: a wrapper in front of gh or git (the
# credential launcher the secret-resolution rule documents, op run, env) is
# looked through, and the launcher's --cwd is the base for relative paths.
assert_payload "credentials.py run --cwd -- gh"   "$(bash_payload "python3 /x/scripts/credentials.py run --profile github --cwd $BODIES -- gh pr comment 1 --body-file work/relative.md")" dirty
assert_payload "llm-auth run -- gh"               "$(bash_payload "llm-auth run --profile github -- gh pr comment 1 --body-file $BODIES/dirty.md")" dirty
assert_payload "env VAR=1 gh"                     "$(bash_payload "env GH_PROMPT_DISABLED=1 gh pr comment 1 --body-file $BODIES/dirty.md")" dirty
assert_payload "op run -- git commit -F"          "$(bash_payload "op run --env-file x.env -- git commit -F $BODIES/dirty-commit.txt")" dirty
# Third Codex review of PR 43: a cd earlier in the command moves the base
# for relative body paths, in both directions.
mkdir -p "$BODIES/cleandir"
printf 'Adds the guard.\n' > "$BODIES/cleandir/dirty.md"
assert_payload "cd then relative body file dirty" "$(bash_payload "cd $BODIES && gh pr comment 1 --body-file work/relative.md")" dirty
assert_payload "cd then relative body file clean" "$(bash_payload "cd $BODIES/cleandir && gh pr comment 1 --body-file dirty.md" "$BODIES")" clean
assert_payload "cd inside a subshell stays there" "$(bash_payload "(cd $BODIES/cleandir && gh pr comment 1 --body-file dirty.md); gh pr comment 1 --body-file dirty.md" "$BODIES")" dirty
assert_payload "cd relative then body file"       "$(bash_payload "cd work; gh pr comment 1 --body-file relative.md" "$BODIES")" dirty
assert_payload "gh pr comment --body-file clean"  "$(bash_payload "gh pr comment 1 --body-file $BODIES/clean.md")" clean
assert_payload "gh api -F body=@ clean"           "$(bash_payload "gh api repos/o/r/issues/1/comments -F body=@$BODIES/clean.md")" clean
assert_payload "git commit -F clean"              "$(bash_payload "git commit -F $BODIES/clean.md")" clean
# A body the detector cannot read is a body it cannot judge, so the command is
# denied rather than passed unchecked (PR 294 adversarial review: an unread
# file used to count as absent, which let every unresolved shape publish).
assert_payload "unreadable body file denies"      "$(bash_payload "gh pr comment 1 --body-file $BODIES/missing.md")" dirty
assert_payload "directory as body file denies"    "$(bash_payload "gh pr comment 1 --body-file $BODIES")" dirty
assert_payload "stdin body file with no source"   "$(bash_payload "gh pr comment 1 --body-file -")" dirty
assert_payload "command still scanned beside file" "$(bash_payload "gh pr create --body-file $BODIES/missing.md --title 'Generated with ${AGENT} Code'")" dirty
# A file named by a non-authoring command is never opened.
assert_payload "grep -F on a dirty file is clean" "$(bash_payload "grep -F x $BODIES/dirty.md")" clean
# Raw fields (-f) are literal strings in gh, never files.
assert_payload "gh api -f body=@ is literal"      "$(bash_payload "gh api repos/o/r/issues/1/comments -f body=@$BODIES/dirty.md")" clean
# Unbalanced quotes do not crash. A publishing command the parser cannot read
# is denied whatever its body holds; one that publishes nothing passes.
assert_payload "unbalanced quotes still read the body" "$(bash_payload "gh pr comment 1 --body-file $BODIES/dirty.md 'oops")" dirty
assert_payload "unbalanced quotes, clean body"    "$(bash_payload "gh pr comment 1 --body-file $BODIES/clean.md 'oops")" dirty
assert_payload "unbalanced quotes, no publisher"  "$(bash_payload "echo 'oops")" clean
# review job 115: a gh call that only reads publishes nothing, so searching
# for an attribution string passes; every writing form is still judged.
assert_payload "gh issue list --search is read-only"  "$(bash_payload "gh issue list --search 'Co-Authored-By: ${AGENT}'")" clean
assert_payload "gh pr view is read-only"              "$(bash_payload "gh pr view 7 --json body --jq 'select(.body | test(\"Generated with ${AGENT} Code\"))'")" clean
assert_payload "gh api GET search is read-only"       "$(bash_payload "gh api search/issues -X GET -f q='Co-Authored-By: ${AGENT}'")" clean
assert_payload "gh api default GET is read-only"      "$(bash_payload "gh api 'search/issues?q=Generated with ${AGENT} Code'")" clean
assert_payload "gh issue create is publishing"        "$(bash_payload "gh issue create --title t --body 'Generated with ${AGENT} Code'")" dirty
assert_payload "gh pr comment --body is publishing"   "$(bash_payload "gh pr comment 1 --body 'Generated with ${AGENT} Code'")" dirty
assert_payload "gh api -f body is publishing"         "$(bash_payload "gh api repos/o/r/issues/1/comments -f body='Generated with ${AGENT} Code'")" dirty
assert_payload "gh api -X PATCH is publishing"        "$(bash_payload "gh api -X PATCH repos/o/r/issues/1 --jq 'Generated with ${AGENT} Code'")" dirty
assert_payload "gh api --method=POST is publishing"   "$(bash_payload "gh api --method=POST repos/o/r/issues --jq 'Generated with ${AGENT} Code'")" dirty
assert_payload "read then publish still publishing"   "$(bash_payload "gh pr view 1; gh pr comment 1 --body 'Generated with ${AGENT} Code'")" dirty
assert_payload "read gh beside git commit"            "$(bash_payload "gh pr view 1 && git commit -m 'x' -m 'Co-Authored-By: ${AGENT} <a@b>'")" dirty
# Quality pass on the read-only change: every other shape that publishes.
assert_payload "read then publish on the next line"   "$(bash_payload "gh pr view 1"$'\n'"gh pr comment 1 --body 'Generated with ${AGENT} Code'")" dirty
assert_payload "gh wrapped in bash -c"                "$(bash_payload "bash -c \"gh pr comment 1 --body 'Generated with ${AGENT} Code'\"")" dirty
assert_payload "gh wrapped in eval"                   "$(bash_payload "eval \"gh issue create --title 'Generated with ${AGENT} Code'\"")" dirty
assert_payload "gh api -fbody= attached"              "$(bash_payload "gh api repos/o/r/issues/1/comments -fbody='Generated with ${AGENT} Code'")" dirty
assert_payload "gh api -iXPOST clustered"             "$(bash_payload "gh api -iXPOST repos/o/r/issues --jq 'Generated with ${AGENT} Code'")" dirty
assert_payload "gh api graphql even with GET"         "$(bash_payload "gh api graphql -X GET -f query='mutation { x(body: \"Generated with ${AGENT} Code\") }'")" dirty
assert_payload "gh -R before the subcommand"          "$(bash_payload "gh -R o/r pr comment 1 --body 'Generated with ${AGENT} Code'")" dirty
assert_payload "gh --repo= before the subcommand"     "$(bash_payload "gh --repo=o/r issue create --title 'Generated with ${AGENT} Code'")" dirty
assert_payload "gh -R then a read verb is read-only"  "$(bash_payload "gh -R o/r issue list --search 'Co-Authored-By: ${AGENT}'")" clean
assert_payload "gh pr checkout is read-only"          "$(bash_payload "gh pr checkout 7 && grep -rn 'Generated with ${AGENT} Code' .")" clean
# Every gh and git invocation names its own body files, not only the first in
# a segment. The first command here reads nothing, so its arguments never
# reach the second one's flags.
assert_payload "gh auth then gh body file on next line" "$(bash_payload "gh auth status"$'\n'"gh pr comment 1 --body-file $BODIES/dirty.md")" dirty
assert_payload "git log then git commit -F next line"   "$(bash_payload "git log -1"$'\n'"git commit -F $BODIES/dirty-commit.txt")" dirty
# A newline ends a simple command, so a cd on its own line moves the base for
# the next line's relative body path, and a continued line stays one command.
assert_payload "second invocation in one segment"       "$(bash_payload "sudo -u git gh pr comment 1 --body-file $BODIES/dirty.md")" dirty
# An earlier invocation covers a later one only when both read files the same
# way: a later git -C elsewhere, or a gh api after a gh pr, is still read.
assert_payload "later git -C elsewhere is still read"   "$(bash_payload "git -C /nonexistent commit -m x git -C $BODIES/work commit -F relative.md")" dirty
assert_payload "later gh api after gh pr is still read" "$(bash_payload "gh pr view 1 gh api repos/o/r/issues/1/comments -F body=@$BODIES/dirty.md")" dirty
# Reading every invocation must stay inside the hook's 3 second budget, since
# a timeout fails open: many invocations in one segment are judged fast.
many="$(python3 -c 'import sys; print(" ".join("gh pr comment 1 --body-file %s/clean.md" % sys.argv[1] for n in range(1000)))' "$BODIES")"
started=$(python3 -c 'import time; print(time.time())')
assert_payload "1000 invocations in one segment"        "$(bash_payload "$many")" clean
elapsed=$(python3 -c "import time; print(int((time.time() - $started) * 1000))")
[ "$elapsed" -lt 1000 ] && record yes "1000 invocations under 1s" "<1000ms" "${elapsed}ms" \
  || record no "1000 invocations under 1s" "<1000ms" "${elapsed}ms"
assert_payload "cd on its own line then relative body"  "$(bash_payload "cd work"$'\n'"gh pr comment 1 --body-file relative.md" "$BODIES")" dirty
assert_payload "body file after a line continuation"    "$(bash_payload "gh pr comment 1 --body-file \\"$'\n'"$BODIES/dirty.md")" dirty
assert_payload "cd continued onto the next line"        "$(bash_payload "cd \\"$'\n'"work && gh pr comment 1 --body-file relative.md" "$BODIES")" dirty
# Self review of the newline change: a heredoc body is data, so its lines move
# no directory, and an escaped backslash before a newline continues nothing.
assert_payload "cd inside a heredoc body moves nothing" "$(bash_payload "cat <<EOF >/dev/null"$'\n'"cd /nonexistent"$'\n'"EOF"$'\n'"gh pr comment 1 --body-file dirty.md" "$BODIES")" dirty
assert_payload "quoted heredoc delimiter moves nothing" "$(bash_payload "cat <<'EOF' >/dev/null"$'\n'"cd /nonexistent"$'\n'"EOF"$'\n'"gh pr comment 1 --body-file dirty.md" "$BODIES")" dirty
assert_payload "escaped backslash then a newline"       "$(bash_payload "echo a\\\\"$'\n'"gh pr comment 1 --body-file $BODIES/dirty.md")" dirty
# Fail-open shapes the self review reproduced in the body file reader.
assert_payload "comment after cd hides no next line"    "$(bash_payload "cd /tmp # enter"$'\n'"gh pr comment 1 --body-file $BODIES/dirty.md")" dirty
assert_payload "gh -R before a body file"               "$(bash_payload "gh -R o/r pr comment 1 --body-file dirty.md" "$BODIES")" dirty
assert_payload "gh --repo= before a body file"          "$(bash_payload "gh --repo=o/r pr comment 1 --body-file dirty.md" "$BODIES")" dirty
assert_payload "gh -F with the path attached"           "$(bash_payload "gh pr comment 1 -F$BODIES/dirty.md")" dirty
assert_payload "gh api -F attached field file"          "$(bash_payload "gh api repos/o/r/issues/1/comments -Fbody=@$BODIES/dirty.md")" dirty
assert_payload "git commit -aF clustered"               "$(bash_payload "git commit -aF $BODIES/dirty-commit.txt")" dirty
assert_payload "git commit -aF with the path attached"  "$(bash_payload "git commit -aF$BODIES/dirty-commit.txt")" dirty
assert_payload "untokenizable heredoc still reads body" "$(bash_payload "cat <<EOF >/dev/null"$'\n'"don't"$'\n'"EOF"$'\n'"gh pr comment 1 --body-file $BODIES/dirty.md")" dirty
assert_payload "body file inside bash -c"               "$(bash_payload "bash -c \"gh pr comment 1 --body-file $BODIES/dirty.md\"")" dirty
assert_payload "gh api graphql -F query=@ file"         "$(bash_payload "gh api graphql -F query=@$BODIES/dirty.md")" dirty
assert_payload "popd returns to the first directory"    "$(bash_payload "pushd /tmp"$'\n'"popd"$'\n'"gh pr comment 1 --body-file dirty.md" "$BODIES")" dirty
assert_payload "subshell closed beside a redirect"      "$(bash_payload "(cd /tmp; true)>/dev/null; gh pr comment 1 --body-file dirty.md" "$BODIES")" dirty
# review jobs 145 and 158: the shell prepass is quote and comment aware.
python3 -c 'import sys; open(sys.argv[1] + "/we\\\nird.md", "w").write(open(sys.argv[1] + "/dirty.md").read())' "$BODIES"
assert_payload "backslash newline inside single quotes" "$(bash_payload "gh pr comment 1 --body-file '$BODIES/we\\"$'\n'"ird.md'")" dirty
assert_payload "heredoc-looking text in quotes"         "$(bash_payload "echo '<<true'"$'\n'"gh pr comment 1 --body-file $BODIES/dirty.md"$'\n'"true")" dirty
assert_payload "substitution in an unquoted heredoc"    "$(bash_payload "cat <<EOF"$'\n'"\$(gh pr comment 1 --body-file $BODIES/dirty.md)"$'\n'"EOF")" dirty
assert_payload "backticks in an unquoted heredoc"       "$(bash_payload "cat <<EOF"$'\n'"\`gh pr comment 1 --body-file $BODIES/dirty.md\`"$'\n'"EOF")" dirty
assert_payload "substitution text in a quoted heredoc"  "$(bash_payload "cat <<'EOF'"$'\n'"\$(gh pr comment 1 --body-file $BODIES/dirty.md)"$'\n'"EOF")" clean
assert_payload "operators inside a comment move nothing" "$(bash_payload "# note; cd /nonexistent"$'\n'"gh pr comment 1 --body-file dirty.md" "$BODIES")" dirty
assert_payload "# inside a word is not a comment"       "$(bash_payload "gh pr comment 1#x --body-file $BODIES/dirty.md")" dirty
# review job 127: a read gh beside a quoted publisher, and a later GET in the
# same segment, do not make a publishing call read-only.
assert_payload "read gh beside a quoted publisher"      "$(bash_payload "gh pr view 1; bash -c \"gh pr comment 1 --body 'Generated with ${AGENT} Code'\"")" dirty
assert_payload "POST then a GET in one segment"         "$(bash_payload "sudo gh api -X POST repos/o/r/issues -f body='Generated with ${AGENT} Code' gh api -X GET user")" dirty
# A session-link line in a pull request body file is published text, not docs
# frontmatter, even when the body file itself sits under docs/.
mkdir -p "$BODIES/docs"
printf -- '---\n%s\n---\nAdds x.\n' "$SESSION_LINK" > "$BODIES/docs/body.md"
assert_payload "gh pr create --body-file session-link" "$(bash_payload "gh pr create --title t --body-file $BODIES/docs/body.md")" dirty

# Adversarial review of PR 294 at f29c0cf: 31 fail-open shapes and 4 false
# positives, each reproduced through the guard. Every case is a row here. The
# block runs the detector in process, so each case names its own HOME, and the
# timing rows measure the detector alone. Agent names are built from pieces.
probe_out="$(python3 - "$DETECT" "$BODIES" <<'PY'
import importlib.util
import json
import os
import sys
import time

spec = importlib.util.spec_from_file_location("attribution_detect", sys.argv[1])
detector = importlib.util.module_from_spec(spec)
spec.loader.exec_module(detector)

A = "Cla" + "ude"
CX = "Co" + "dex"
OA = "Open" + "AI"
CU = "cur" + "sor"
CO = "Co-Auth" + "ored-By: "
TRAILER = CO + A + " <bot@example.org>"
root = os.path.join(sys.argv[2], "probe")
home = os.path.join(root, "home")
sub = os.path.join(root, "sub")
os.makedirs(sub)
os.makedirs(home)


def write(path, text):
    with open(path, "w") as handle:
        handle.write(text)


for path in (os.path.join(root, "b.md"), os.path.join(sub, "only-sub.md"), os.path.join(home, "hb.md")):
    write(path, "Summary\n\n" + TRAILER + "\n")
write(os.path.join(root, "clean.md"), "Summary\n\nNothing else.\n")
write(os.path.join(sub, "b.md"), "Summary\n\nNothing else.\n")
write(os.path.join(root, "big.json"), '{"body": "Summary\\n\\n' + TRAILER + '"}' + " " * (1024 * 1024 + 10))
write(os.path.join(root, "big.txt"), "Release\n\n" + TRAILER + "\n" + ("x" * 79 + "\n") * 13200)
with open(os.path.join(root, "gql.json"), "w") as handle:
    json.dump({"query": "mutation($b:String!){addComment(input:{body:$b}){clientMutationId}}", "variables": {"b": "Summary\n\n" + TRAILER}}, handle)
B = os.path.join(root, "b.md")
C = os.path.join(root, "clean.md")

CASES = [
    # P0: the shell prepass misread these and dropped the gh line.
    ("arith shift read as heredoc", f"echo $((1<<true))\ngh pr create --title t --body-file {B}\ntrue", "deny"),
    ("partly quoted heredoc delimiter", f"cat <<true'x' >/dev/null\ntruex\ngh pr create --title t --body-file {B}\ntrue", "deny"),
    ("ansi-c escaped quote", f"echo $'a\\' <<true' #'\ngh pr create --title t --body-file {B}\ntrue", "deny"),
    ("comment misread in $() in dquotes", f'echo "$(echo " #")"; gh pr create --title t --body-file {B}', "deny"),
    # P0: program names and text the shell rebuilds.
    ("quoted program name", f'"gh" pr create --title t --body "{TRAILER}"', "deny"),
    ("escaped program name", f'g\\h pr create --title t --body "{TRAILER}"', "deny"),
    ("quoted subcommand", f'gh "pr" create --title t --body "{TRAILER}"', "deny"),
    ("string concatenation", f'gh pr create --title t --body "{CO}Cla""ude <x@example.org>"', "deny"),
    ("continuation inside dquotes", f'gh pr create --title t --body "{CO}Cla\\\nude <x@example.org>"', "deny"),
    ("ansi-c hex escape", f"gh pr create --title t --body $'{CO}Cl\\x61ude <x@example.org>'", "deny"),
    # P0: bodies the flag parsers never saw.
    ("body via $(cat file)", f'gh pr create --title t --body "$(cat {B})"', "deny"),
    ("body via $(< file)", f'gh pr create --title t --body "$(< {B})"', "deny"),
    ("stdin redirect body-file -", f"gh pr create --title t --body-file - < {B}", "deny"),
    ("cat pipe body-file -", f"cat {B} | gh pr create --title t --body-file -", "deny"),
    ("git commit -F - redirect", f"git commit -F - < {B}", "deny"),
    ("git tag -m $(cat)", f'git tag -a v9 -m "$(cat {B})"', "deny"),
    ("xargs path", f"echo {B} | xargs gh pr create --title t --body-file", "deny"),
    ("var path same command", f'F={B}; gh pr create --title t --body-file "$F"', "deny"),
    # P0: directory tracking.
    ("cd -P then relative", "cd -P sub && gh pr create --title t --body-file only-sub.md", "deny"),
    ("cd -- then relative", "cd -- sub && gh pr create --title t --body-file only-sub.md", "deny"),
    ("bare cd to HOME then relative", "cd && gh pr create --title t --body-file hb.md", "deny"),
    ("builtin cd then relative", "builtin cd sub && gh pr create --title t --body-file only-sub.md", "deny"),
    ("cd in a brace group", "{ cd sub; } && gh pr create --title t --body-file only-sub.md", "deny"),
    ("git commit -F after cd -P", "cd -P sub && git commit -F only-sub.md", "deny"),
    # P0: size cap, unread request shapes, aliases, backtracking.
    ("gh api --input over 1MB", f"gh api repos/o/r/issues/1/comments --input {root}/big.json", "deny"),
    ("git tag -F over 1MB", f"git tag -a v9 -F {root}/big.txt", "deny"),
    ("gh api graphql variables", f"gh api graphql --input {root}/gql.json", "deny"),
    ("gh gist create file", f"gh gist create {B}", "deny"),
    ("git alias via -c", f"git -c alias.k=commit k -F {B}", "deny"),
    ("gh alias", f"gh pc --title t --body-file {B}", "deny"),
    ("git -c chain then trailer", "git" + " -c" * 36 + f' x; gh pr create --title t --body "{TRAILER}"', "deny"),
    # P2: false positives.
    ("clean commit", 'git commit -m "fix: parse config"', "allow"),
    ("technical mention, created by", 'git commit -m "fix: parse config files ' + "cre" + "ated by " + CX + ' CLI"', "allow"),
    ("technical mention, built with", 'git commit -m "feat: adapter ' + "bu" + "ilt with " + OA + ' SDK"', "allow"),
    ("human co-author at a vendor domain", f'git commit -m "x\n\n{CO}Jane Doe <jane@{CU}.com>"', "allow"),
    ("commit then an unrelated grep", f'git commit -m "fix" && grep -rn "{TRAILER}" .', "allow"),
    # Controls the fixes must keep.
    ("two-line body file", f"echo hi\ngh pr create --title t --body-file {B}", "deny"),
    ("cd sub then relative", "cd sub && gh pr create --title t --body-file only-sub.md", "deny"),
    ("cd sub then relative clean", "cd sub && gh pr create --title t --body-file b.md", "allow"),
    # Resolved shapes: a body the parser can read in full is judged, not denied.
    ("quoted heredoc stdin clean", "gh pr create --title t --body-file - <<'EOF'\nSummary\nEOF", "allow"),
    ("quoted heredoc stdin dirty", f"gh pr create --title t --body-file - <<'EOF'\n{TRAILER}\nEOF", "deny"),
    ("herestring stdin dirty", f"gh pr create --title t --body-file - <<< '{TRAILER}'", "deny"),
    ("body via $(cat clean)", f'gh pr create --title t --body "$(cat {C})"', "allow"),
    ("var path clean", f'F={C}; gh pr create --title t --body-file "$F"', "allow"),
    ("HOME variable in a body path", "gh pr create --title t --body-file $HOME/hb.md", "deny"),
    ("body written by a heredoc first", f"cat > {root}/made.md <<'EOF'\n{TRAILER}\nEOF\ngh pr create --title t --body-file {root}/made.md", "deny"),
    ("clean body written by a heredoc first", f"cat > {root}/made2.md <<'EOF'\nSummary\nEOF\ngh pr create --title t --body-file {root}/made2.md", "allow"),
    # An argument built at run time may carry a flag (-m...), so it is not
    # judged as a plain positional; a literal prefix keeps it a path.
    ("substituted pull request number", f"gh pr comment $(gh pr view --json number -q .number) --body-file {C}", "deny"),
    ("substituted commit in an api path", f"gh api repos/o/r/commits/$(git rev-parse HEAD)/comments -F body=@{C}", "allow"),
    ("unset variable as a title", f'gh pr create --title "$NO_SUCH_TITLE_VAR" --body-file {C}', "deny"),
    ("missing body file", f"gh pr create --title t --body-file {root}/absent.md", "deny"),
    ("script heredoc into bash", f"bash <<'EOF'\ngh pr create --title t --body \"{TRAILER}\"\nEOF", "deny"),
    ("script piped into sh", f"echo 'gh pr create --title t --body-file {B}' | sh", "deny"),
    ("gh extension without body flags", "gh dash", "allow"),
    ("gh co default alias", "gh co 12", "allow"),
    ("gh text mentioned in a commit message", 'git commit -m "docs: explain gh pr create --body-file usage"', "allow"),
    ("trailer flag on git commit", f'git commit -m x --trailer "{TRAILER}"', "deny"),
    ("raw api field carries a trailer", f"gh api repos/o/r/issues/1/comments -f 'body={TRAILER}'", "deny"),
    ("footer as the trailing clause", 'git commit -m "fix: x. ' + "Gene" + "rated with " + A + ' Code"', "deny"),
    ("footer in parentheses", 'git commit -m "fix: x (' + "gene" + "rated by " + A + ')"', "deny"),
    ("deep substitution nesting", "gh pr create --title t --body " + "$(" * 3000 + "x" + ")" * 3000, "deny"),
    # Everyday publishing shapes stay allowed when clean.
    ("commit message from a cat heredoc", "git commit -m \"$(cat <<'EOF'\nfix: x\n\nBody.\nEOF\n)\"", "allow"),
    ("dirty commit message from a cat heredoc", f"git commit -m \"$(cat <<'EOF'\nfix: x\n\n{TRAILER}\nEOF\n)\"", "deny"),
    ("pull request body from a cat heredoc", "gh pr create --title t --body \"$(cat <<'EOF'\n- item\nEOF\n)\"", "allow"),
    ("body that opens with a list dash", 'gh pr create --title t --body "- fixed a thing"', "allow"),
    ("handoff comment from a file", f"gh pr comment 294 --repo o/r --body-file {C}", "allow"),
    ("git -C commit -F clean", f"git -C {root} commit -F {C}", "allow"),
    ("merge with no body", "gh pr merge 5 --squash", "allow"),
    ("chained add and commit", f'cd {root} && git add -A && git commit -m "fix: x"', "allow"),
    ("push", "git push -u origin HEAD", "allow"),
    # Correctness pass on 763ae4b: each shape reproduced, then fixed.
    ("program name from a variable", f"g=git; $g commit -m '{TRAILER}'", "deny"),
    ("program name from a substitution", f"$(echo git) commit -m '{TRAILER}'", "deny"),
    ("program name through a tilde path", f"~/../../usr/bin/git commit -m '{TRAILER}'", "deny"),
    ("program name as a glob", f"/usr/bin/gi[t] commit -m '{TRAILER}'", "deny"),
    ("program name as a brace expansion", f"{{git,}} commit -m '{TRAILER}'", "deny"),
    ("program name as a zsh equals path", f"=git commit -m '{TRAILER}'", "deny"),
    ("flags from a function's arguments", f"f() {{ git commit \"$@\"; }}; f -m '{TRAILER}'", "deny"),
    ("flags from set --", f"set -- -m '{TRAILER}'; git commit \"$@\"", "deny"),
    ("flags from an array", f"a=(-m '{TRAILER}'); git commit \"${{a[@]}}\"", "deny"),
    ("flags from an unquoted variable", f"x='-m{CO}{A}'; git commit $x", "deny"),
    ("variable reset by printf -v", 'M=clean; printf -v M "%s" x; git commit -m "$M"', "deny"),
    ("variable reset by eval", "M=clean; eval 'M=$(date)'; git commit -m \"$M\"", "deny"),
    ("variable reset by source", 'M=clean; source /dev/null; git commit -m "$M"', "deny"),
    ("body from /dev/stdin", "printf 'x' | git commit -F /dev/stdin", "deny"),
    ("body from /dev/fd/0", f"git commit -F /dev/fd/0 < {B}", "deny"),
    ("case pattern inside a substitution", 'echo "$(case a in a) printf x | git commit -F -;; esac)"', "deny"),
    ("printf format builds a trailer", f"printf 'Co-Auth%s: Cl%sude <x@y.org>\\n' ored-By aude > {root}/m.txt; git commit -F {root}/m.txt", "deny"),
    ("echo -e escapes build a trailer", f"echo -e '\\x43o-Auth" + "ored-By: " + A + f" <x@y.org>' > {root}/m2.txt; git commit -F {root}/m2.txt", "deny"),
    ("trailer flag with an equals sign", "git commit -m x --trailer 'Co-auth" + "ored-by=" + A + " <x@y.org>'", "deny"),
    ("glab api field", f"glab api projects/1/issues/1/notes -f body='{TRAILER}'", "deny"),
    ("git am of a patch", f"git am {B}", "deny"),
    ("git editor override", f"git -c core.editor='cp {B}' commit", "deny"),
    ("GIT_EDITOR override", f"GIT_EDITOR='cp {B}' git commit", "deny"),
    ("op run wrapper with a clean body", f"op run --env-file .env -- gh pr comment 1 --body-file {C}", "allow"),
    ("timeout wrapper with a clean body", f"timeout 30 gh pr comment 1 --body-file {C}", "allow"),
    ("NUL in a body path", "git commit -F $'/tmp/a\\x00b'", "deny"),
    ("NUL in a -C path", "git -C $'/a\\x00' commit -F x", "deny"),
    # Clean text, so allowed; the row guards the time (every row is held to
    # 0.5 s), which was 9.7 s when each copy was read and scanned again.
    ("many large substitutions", f"git commit " + f'-m "$(cat {root}/near-limit.txt)" ' * 69, "allow"),
]
write(os.path.join(root, "near-limit.txt"), "x" * (1024 * 1024 - 10))
os.mkfifo(os.path.join(root, "pipe"))
CASES.append(("body from a FIFO", f"git commit -F {root}/pipe", "deny"))

failures = []
for label, command, expect in CASES:
    os.environ["HOME"] = home
    payload = {"tool_name": "Bash", "cwd": root, "tool_input": {"command": command}}
    started = time.time()
    got = "deny" if detector.detect_in_payload(payload) else "allow"
    took = time.time() - started
    if got != expect:
        failures.append(f"{label}: expected={expect} got={got}")
    elif took > 0.5:
        failures.append(f"{label}: {took:.2f}s, over 0.5s")

# Every regex on untrusted text finishes a 10 KB adversarial input quickly.
TEXTS = [
    ("repeated trailer keyword", CO * 700),
    ("open brackets", "[" * 10000),
    ("unclosed links", "[a](http://x" * 800),
    ("repeated footer verb", ("Gene" + "rated with ") * 700),
    ("quote then dashes", '"' + "-" * 10000),
    ("quotes and dashes", '"-' * 5000),
]
for label, text in TEXTS:
    started = time.time()
    detector.detect(text)
    detector.strip(text)
    took = time.time() - started
    if took > 0.5:
        failures.append(f"timing {label}: {took:.2f}s")
COMMANDS = [
    ("git -c chain", "git" + " -c" * 3300 + " x"),
    ("arithmetic opens", "echo " + "$((" * 3300),
    ("substitution opens", "gh pr create --body " + "$(" * 5000),
    ("heredoc openers", "cat " + "<<a " * 2500),
    ("quoted substitutions", 'echo "' + '$("' * 3300),
    ("cd chain", "cd x; " * 1700 + "gh pr create --title t --body-file b.md"),
    ("many words", "gh pr create --title t " + "--body-file b.md " * 600),
    ("git invocations with distinct -c", "".join(f"git -c a.b={n} commit -m x " for n in range(700))),
]
for label, command in COMMANDS:
    payload = {"tool_name": "Bash", "cwd": root, "tool_input": {"command": command}}
    started = time.time()
    detector.detect_in_payload(payload)
    took = time.time() - started
    if took > 0.5:
        failures.append(f"timing {label}: {took:.2f}s")
started = time.time()
detector.detect_in_payload({"tool_name": "Write", "tool_input": {"file_path": "a/" * 5000 + "x", "content": "x"}})
if time.time() - started > 0.5:
    failures.append("timing long docs path")

print(len(CASES) + len(TEXTS) + len(COMMANDS) + 1, len(failures))
for failure in failures:
    print(failure)
PY
)" || probe_out="0 1
probe block crashed"
probe_total="$(printf '%s\n' "$probe_out" | head -n 1 | cut -d' ' -f1)"
probe_failed="$(printf '%s\n' "$probe_out" | head -n 1 | cut -d' ' -f2)"
PASS=$((PASS + probe_total - probe_failed))
FAIL=$((FAIL + probe_failed))
printf '%s\n' "$probe_out" | tail -n +2 | sed 's/^/  attribution-detect.py FAIL  /' >&2

# Non-UTF-8 input is judged, never a crash: a commit message in a legacy
# encoding still has its attribution found and stripped, and strip keeps every
# other byte exactly as it was.
latin=$(printf 'fix: caf\xe9\n\nCo-Authored-By: %s <a@b>\n' "$AGENT" | python3 "$DETECT" detect 2>&1 || true)
[ "$latin" = "co-author-trailer" ] && record yes "detect on non-UTF-8 text" co-author-trailer "$latin" \
  || record no "detect on non-UTF-8 text" co-author-trailer "$latin"
printf 'fix: caf\xe9\n\nCo-Authored-By: %s <a@b>\n' "$AGENT" | python3 "$DETECT" strip > "$BODIES/latin-out" 2>&1 || true
printf 'fix: caf\xe9\n' > "$BODIES/latin-want"
if cmp -s "$BODIES/latin-out" "$BODIES/latin-want"; then
  record yes "strip keeps non-UTF-8 bytes" same same
else
  record no "strip keeps non-UTF-8 bytes" "fix: caf<e9>" "$(od -c "$BODIES/latin-out" | head -n 3 | tr '\n' ' ')"
fi

# Every tool is now routed through the guard, so a local bookkeeping tool whose
# fields are never published is not judged on them.
assert_payload "TodoWrite is not published"      "{\"tool_name\":\"TodoWrite\",\"tool_input\":{\"todos\":[{\"content\":\"Co-Authored-By: ${AGENT} trailer to strip\"}]}}" clean
assert_payload "Read carries no message field"   "{\"tool_name\":\"Read\",\"tool_input\":{\"file_path\":\"$BODIES/dirty.md\"}}" clean

printf 'attribution-detect.py: %d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
